// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const CreateProjectOptions: CLICommandOption[] = [
  {
    name: "project-type",
    type: "string",
    description: "New Project",
    required: true,
    choices: ["copilot-agent-type", "bot-type"],
  },
  {
    name: "capabilities",
    type: "string",
    description: "App Features Using Agents",
    choices: ["api-plugin", "declarative-agent"],
  },
  {
    name: "with-plugin",
    type: "string",
    description: "Create Declarative Agent",
    default: "no",
    choices: ["no", "yes"],
  },
  {
    name: "api-plugin-type",
    type: "string",
    description: "Create API Plugin",
    default: "new-api",
    choices: ["new-api", "api-spec"],
  },
  {
    name: "api-auth",
    type: "string",
    description: "Authentication Type",
    default: "none",
    choices: ["none", "api-key", "bearer-token", "microsoft-entra", "oauth"],
  },
  {
    name: "custom-copilot-rag",
    type: "string",
    description: "Chat With Your Data",
    default: "custom-copilot-rag-customize",
    choices: [
      "custom-copilot-rag-customize",
      "custom-copilot-rag-azureAISearch",
      "custom-copilot-rag-customApi",
      "custom-copilot-rag-microsoft365",
    ],
  },
  {
    name: "openapi-spec-location",
    type: "string",
    shortName: "a",
    description: "OpenAPI description document location.",
  },
  {
    name: "api-operation",
    type: "array",
    description: "Select Operation(s) Teams Can Interact with",
  },
  {
    name: "bot-host-type-trigger",
    type: "string",
    description: "Select triggers",
    choices: ["http-express", "http-and-timer-functions", "http-functions", "timer-functions"],
  },
  {
    name: "programming-language",
    type: "string",
    description: "Programming Language",
    choices: ["javascript", "typescript", "csharp", "python"],
  },
  {
    name: "llm-service",
    type: "string",
    description: "Service for Large Language Model (LLM)",
    default: "llm-service-azure-openai",
    choices: ["llm-service-azure-openai", "llm-service-openai"],
  },
  {
    name: "azure-openai-key",
    type: "string",
    description: "Azure OpenAI Key",
  },
  {
    name: "azure-openai-endpoint",
    type: "string",
    description: "Azure OpenAI Endpoint",
  },
  {
    name: "azure-openai-deployment-name",
    type: "string",
    description: "Azure OpenAI Deployment Name",
  },
  {
    name: "openai-key",
    type: "string",
    description: "OpenAI Key",
  },
  {
    name: "folder",
    type: "string",
    description: "Workspace Folder",
    required: true,
    default: "C:\\Users\\nintan\\TeamsApps",
  },
  {
    name: "app-name",
    type: "string",
    description: "Application Name",
    required: true,
  },
];
export const CreateProjectArguments: CLICommandArgument[] = [];
