// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandArgument, CLICommandOption } from "@microsoft/teamsfx-api";

export const CreateProjectOptions: CLICommandOption[] = [
  {
    name: "project-type",
    type: "string",
    description: "New Project",
    required: true,
    choices: [
      "copilot-agent-type",
      "custom-copilot-type",
      "bot-type",
      "tab-type",
      "me-type",
      "outlook-addin-type",
      "start-with-github-copilot",
    ],
  },
  {
    name: "with-plugin",
    type: "string",
    description: "Whether to add API plugin for your declarative Copilot.",
    choices: ["da-without-plugin", "da-with-plugin"],
  },
  {
    name: "api-plugin-type",
    type: "string",
    description: "API plugin type.",
    default: "new-api",
    choices: ["new-api", "api-spec", "existing-plugin"],
  },
  {
    name: "api-auth",
    type: "string",
    description: "The authentication type for the API.",
    default: "none",
    choices: ["none", "api-key", "oauth"],
  },
  {
    name: "openapi-spec-location",
    type: "string",
    shortName: "a",
    description: "OpenAPI description document location.",
  },
  {
    name: "api-operation",
    type: "array",
    description: "Select Operation(s) Teams Can Interact with",
  },
  {
    name: "plugin-manifest-path",
    type: "string",
    description: "Plugin manifest path.",
  },
  {
    name: "plugin-opeanapi-spec-path",
    type: "string",
    description: "OpenAPI description document used for your API plugin.",
  },
  {
    name: "capabilities",
    type: "string",
    description: "App Features Using Teams AI Library",
    choices: ["custom-copilot-basic", "custom-copilot-rag", "custom-copilot-agent"],
  },
  {
    name: "custom-copilot-rag",
    type: "string",
    description: "Chat With Your Data",
    default: "custom-copilot-rag-customize",
    choices: [
      "custom-copilot-rag-customize",
      "custom-copilot-rag-azureAISearch",
      "custom-copilot-rag-customApi",
      "custom-copilot-rag-microsoft365",
    ],
  },
  {
    name: "custom-copilot-agent",
    type: "string",
    description: "AI Agent",
    default: "custom-copilot-agent-new",
    choices: ["custom-copilot-agent-new", "custom-copilot-agent-assistants-api"],
  },
  {
    name: "llm-service",
    type: "string",
    description: "Service for Large Language Model (LLM)",
    default: "llm-service-azure-openai",
    choices: ["llm-service-azure-openai", "llm-service-openai"],
  },
  {
    name: "azure-openai-key",
    type: "string",
    description: "Azure OpenAI Key",
  },
  {
    name: "azure-openai-endpoint",
    type: "string",
    description: "Azure OpenAI Endpoint",
  },
  {
    name: "azure-openai-deployment-name",
    type: "string",
    description: "Azure OpenAI Deployment Name",
  },
  {
    name: "openai-key",
    type: "string",
    description: "OpenAI Key",
  },
  {
    name: "bot-host-type-trigger",
    type: "string",
    description: "Specifies the trigger for `Chat Notification Message` app template.",
    choices: ["http-express", "http-and-timer-functions", "http-functions", "timer-functions"],
  },
  {
    name: "spfx-solution",
    type: "string",
    description: "SharePoint Solution",
    default: "new",
    choices: ["new", "import"],
  },
  {
    name: "spfx-install-latest-package",
    type: "boolean",
    description: "SharePoint Framework",
    default: true,
  },
  {
    name: "spfx-framework-type",
    type: "string",
    description: "Framework",
    default: "react",
    choices: ["react", "minimal", "none"],
  },
  {
    name: "spfx-webpart-name",
    type: "string",
    description: "Name for SharePoint Framework Web Part",
    default: "helloworld",
  },
  {
    name: "spfx-folder",
    type: "string",
    description: "SPFx solution folder",
  },
  {
    name: "me-architecture",
    type: "string",
    description: "The authentication type for the API.",
    default: "new-api",
    choices: ["new-api", "api-spec", "bot-plugin"],
  },
  {
    name: "addin-project-folder",
    type: "string",
    description: "Existing add-in project folder",
  },
  {
    name: "addin-project-manifest",
    type: "string",
    description: "Select import project manifest file",
  },
  {
    name: "programming-language",
    type: "string",
    description: "Programming Language",
    choices: ["javascript", "typescript", "csharp", "python"],
  },
  {
    name: "folder",
    type: "string",
    description: "Workspace Folder",
    required: true,
    default: "C:\\Users\\nintan\\TeamsApps",
  },
  {
    name: "app-name",
    type: "string",
    description: "Application Name",
    required: true,
  },
];
export const CreateProjectArguments: CLICommandArgument[] = [];
