// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { CLICommandOption, CLICommandArgument } from "@microsoft/teamsfx-api";

export const ShareOptions: CLICommandOption[] = [
  {
    name: "scope",
    type: "string",
    description: "Share the app",
    required: true,
    choices: ["tenant", "specific-users", "owners"],
  },
  {
    name: "email",
    type: "string",
    description: "Email address of specific users.",
  },
];
export const ShareArguments: CLICommandArgument[] = [];
