// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

// Static baseline files for a converted Open Plugin project. Anything
// variable (manifest, skill folders, command files, icons) is written
// programmatically by generator.ts. The constants below are emitted verbatim.

const APP_NAME_TOKEN = "__APP_NAME__";

export const GITIGNORE_CONTENT = `# TeamsFx files
env/.env.*.user
env/.env.local
.localConfigs
appPackage/build

# dependencies
node_modules/

# misc
.env
.deployment
.DS_Store

# generated files
appPackage/.generated
`;

export const VSCODE_LAUNCH_JSON = `{
  "version": "0.2.0",
  "configurations": []
}
`;

export const VSCODE_SETTINGS_JSON = `{
  "debug.onTaskErrors": "abort"
}
`;

export const VSCODE_EXTENSIONS_JSON = `{
  "recommendations": [
    "TeamsDevApp.ms-teams-vscode-extension"
  ]
}
`;

export const ENV_DEV_CONTENT = `# Built-in environment variables
TEAMSFX_ENV=dev
APP_NAME_SUFFIX=dev

# Generated during provision
TEAMS_APP_ID=
`;

const M365_AGENTS_YML_TEMPLATE = `# yaml-language-server: $schema=https://aka.ms/m365-agents-toolkits/v1.11/yaml.schema.json
# Generated by 'atk convert openplugin'.
version: v1.11

environmentFolderPath: ./env

# Triggered when 'atk provision' is executed
provision:
  - uses: teamsApp/create
    with:
      name: ${APP_NAME_TOKEN}\${{APP_NAME_SUFFIX}}
    writeToEnvironmentFile:
      teamsAppId: TEAMS_APP_ID

  - uses: teamsApp/zipAppPackage
    with:
      manifestPath: ./appPackage/manifest.json
      outputZipPath: ./appPackage/build/appPackage.\${{TEAMSFX_ENV}}.zip
      outputFolder: ./appPackage/build

  - uses: teamsApp/update
    with:
      appPackagePath: ./appPackage/build/appPackage.\${{TEAMSFX_ENV}}.zip

# Triggered when 'atk publish' is executed
publish:
  - uses: teamsApp/zipAppPackage
    with:
      manifestPath: ./appPackage/manifest.json
      outputZipPath: ./appPackage/build/appPackage.\${{TEAMSFX_ENV}}.zip
      outputFolder: ./appPackage/build
  - uses: teamsApp/update
    with:
      appPackagePath: ./appPackage/build/appPackage.\${{TEAMSFX_ENV}}.zip
  - uses: teamsApp/publishAppPackage
    with:
      appPackagePath: ./appPackage/build/appPackage.\${{TEAMSFX_ENV}}.zip
    writeToEnvironmentFile:
      publishedAppId: TEAMS_APP_PUBLISHED_APP_ID
`;

const README_TEMPLATE = `# ${APP_NAME_TOKEN}

This project was scaffolded by \`atk convert openplugin\`.

## What was converted

- \`appPackage/manifest.json\` is a Microsoft 365 Unified App Manifest (devPreview).
- \`appPackage/skills/\` contains each \`SKILL.md\` copied verbatim from the source plugin and referenced by the manifest \`agentSkills[]\` array.
- \`appPackage/commands/\` (if present) holds the slash-command Markdown files from the source plugin. They are copied for forward compatibility but are not yet referenced by MOS3.
- \`agentConnectors[]\` in the manifest reflects remote MCP servers from \`.mcp.json\`. Stdio (local) MCP servers were skipped — convert them by hand into \`localMcpServer\` entries if needed.

## Next steps

1. Review developer metadata in \`appPackage/manifest.json\` (id, packageName, name, description, urls).
2. For every \`agentConnectors[*].toolSource.remoteMcpServer.authorization\` entry with \`type === "OAuthPluginVault"\`, register a matching credential reference in the Microsoft 365 Developer Portal using the \`referenceId\` value baked into the manifest.
3. Build the upload package: \`atk teamsapp package\`.
4. Validate: \`atk teamsapp validate --file-path ./appPackage/build/appPackage.dev.zip\`.

This project requires the \`TEAMSFX_AGENT_SKILLS\` feature flag while \`agentSkills\` support is being rolled out.
`;

function applyAppName(template: string, appName: string): string {
  return template.split(APP_NAME_TOKEN).join(appName);
}

export function renderM365AgentsYml(appName: string): string {
  return applyAppName(M365_AGENTS_YML_TEMPLATE, appName);
}

export function renderReadme(appName: string): string {
  return applyAppName(README_TEMPLATE, appName);
}
