// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface AddKnowledgeInputs extends Inputs {
  /** @description Add Knowledge */
  "knowledge-source"?: "web-search" | "oneDrive-sharePoint" | "embedded-knowledge";
  /** @description Select Search Type */
  "search-type"?: string;
  /** @description Web Content */
  "web-content"?: string;
  /** @description OneDrive or SharePoint Content */
  oneDriveSharePointURL?: string;
  /** @description OneDrive or SharePoint Content */
  oneDriveSharePointContent?: string;
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
}
