// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

/****************************************************************************************
 *                            NOTICE: AUTO-GENERATED                                    *
 ****************************************************************************************
 * This file is automatically generated by script "./src/question/generator.ts".        *
 * Please don't manually change its contents, as any modifications will be overwritten! *
 ***************************************************************************************/

import { Inputs } from "@microsoft/teamsfx-api";

export interface AddPluginInputs extends Inputs {
  /** @description Add an Action */
  "api-plugin-type"?: "api-spec" | "mcp";
  /** @description OpenAPI Spec Document */
  "openapi-spec-type"?: "enter-url-or-open-local-file" | "search-api";
  /** @description OpenAPI Description Document */
  "openapi-spec-location"?: string;
  /** @description Select Operation(s) Copilot Can Interact with */
  "api-operation"?: string[];
  /** @description Search OpenAPI Description Document */
  "search-openapi-spec-query"?: string;
  /** @description Select OpenAPI Description Document */
  "select-openapi-spec"?: string;
  /** @description MCP Server URL */
  "mcp-da-server-url"?: string;
  /** @description MCP Tools Definition File */
  "mcp-tools-file-path"?: string;
  /** @description Select Authentication Type */
  "mcp-da-auth-type"?: "oauth" | "entraSSO";
  /** @description Select Teams manifest.json File */
  "manifest-path"?: string;
}
