name: setup project
description: setup project by default installing dependencies and running setup script
inputs:
  setup:  # id of input
    description: 'setup project'
    required: true
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - uses: pnpm/action-setup@v4

    - name: Restore pnpm cache (if any)
      id: pnpm_cache
      uses: cache/restore@v4
      with:
        path: |
          '**/node_modules'
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/pnpm-lock.yaml') }}
    
    - name: Setup project
      if: ${{ inputs.setup == 'true' }}
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 5
        command: |
          npm run setup

    - name: Save pnpm cache (if changed)
      uses: cache/save@v4
      if: steps.pnpm_cache.outputs.cache-hit != 'true'
      with:
        path: |
          '**/node_modules'
        key: ${{ steps.pnpm_cache.outputs.cache-primary-key }}
