name: CD
run-name: CD-${{ github.run_id }}-${{ github.ref_name }}-${{ inputs.preid }}-${{ inputs.series }}
on:
  workflow_dispatch:
    inputs:
      preid:
        description: "preid name(alpha, preview, rc, stable)"
        required: true
        default: "alpha"
      series:
        description: "release sprint series name"
        required: false
        default: ""
      pkgs:
        type: string
        required: false
        description: "Please enter the package names you want to publish, such as cli, vscode, ui, sdk, server and template. Please separate multiple entries with spaces"
        default: ""
      vsrelease:
        type: boolean
        default: false
        description: "Whether to release vs product"
      vstemplate:
        type: boolean
        default: false
        description: "Whether to release vs template"
      goproduct:
        type: boolean
        default: false
        description: "Whether to release TTK as publish product"
      skipmarkdownandvulnerabilitycheck:
        type: boolean
        default: false
        description: "Whether to skip Markdown files and vulnerability check"
      run_test_cases:
        type: boolean
        default: false
        description: "Whether to run test cases after CD"
  schedule:
    - cron: "15 11 * * *"  # UTC+8 19:15 make sure the daily build generated before the daily test pipeline trigger

permissions:
  actions: write
  contents: write

jobs:
  cd:
    runs-on: ubuntu-latest
    outputs:
      markdown-check-result: ${{ steps.markdown-check.outcome }}
      security-check-vsc-result: ${{ steps.security-check-vsc.outcome }}
      security-check-vs-result: ${{ steps.security-check-vs.outcome }}
      markdown-check-samples-result: ${{ steps.markdown-check-samples.outcome }}
      security-check-samples-result: ${{ steps.security-check-samples.outcome }}
    env:
      CI: true
      PREID: ${{ github.event.inputs.preid }}
      VS_RELEASE: ${{ github.event.inputs.vsrelease }}
      PRODUCTION: ${{ github.event.inputs.goproduct }}
    steps:
      - id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_GITHUB_APP_ID }}
          private-key: ${{ secrets.APP_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - name: Install wine64
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
          sudo apt update
          sudo apt install --install-recommends winehq-stable -y
          sudo ln -s /usr/bin/wine /usr/bin/wine64
          wine --version
          wine64 --version

      - name: Setup git
        run: |
          git config --global user.name 'wh-alice'
          git config --global user.email 'alicewan@microsoft.com'

      - name: manage pkgs to release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: bash .github/scripts/lerna.sh ${{github.event.inputs.pkgs}}

      - name: Setup project
        run: |
          npm run setup

      - name: release templates' RC version to github
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.preid == 'rc' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          prerelease: true
          tag: "templates@0.0.0-rc"
          artifacts: |
            ${{ github.workspace }}/templates/build/fallback/common.zip
            ${{ github.workspace }}/templates/build/fallback/js.zip
            ${{ github.workspace }}/templates/build/fallback/ts.zip
            ${{ github.workspace }}/templates/build/fallback/python.zip
            ${{ github.workspace }}/templates/build/fallback/csharp.zip
            ${{ github.workspace }}/templates/build/metadata.zip
          allowUpdates: true
          removeArtifacts: true
