name: CD (test)
on:
  workflow_dispatch:
    inputs:
      vsrelease:
        type: boolean
        default: true
        description: "Whether to release VS template"

permissions:
  contents: write

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_GITHUB_APP_ID }}
          private-key: ${{ secrets.APP_GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4

      - name: Setup project
        run: npm run setup

      - name: Release RC VS templates to GitHub
        if: ${{ github.event.inputs.vsrelease == 'true' }}
        uses: ncipollo/release-action@v1.10.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          tag: "templates-vs@0.0.0-rc"
          name: "templates-vs@0.0.0-rc"
          body: "VS Templates RC release test"
          commit: ${{ github.sha }}
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            ${{ github.workspace }}/templates/build/fallback/csharp.zip
            ${{ github.workspace }}/templates/build/metadata.zip